insert into Airport (airport_id, country, city, name) values (1, 'China', 'Shuinan', 'Newtok Airport');
insert into Airport (airport_id, country, city, name) values (2, 'Namibia', 'Grootfontein', 'RNZAF Base Ohakea');
insert into Airport (airport_id, country, city, name) values (3, 'Netherlands', 'Amsterdam', 'Portland International Airport');
insert into Airport (airport_id, country, city, name) values (4, 'Indonesia', 'Nagasari', 'Sirri Island Airport');
insert into Airport (airport_id, country, city, name) values (5, 'Indonesia', 'Krajan', 'Malevo Airport');
insert into Airport (airport_id, country, city, name) values (6, 'Russia', 'Velikiy Novgorod', 'Naracoorte Airport');
insert into Airport (airport_id, country, city, name) values (7, 'Gambia', 'Baro Kunda', 'Ravenna Airport');
insert into Airport (airport_id, country, city, name) values (8, 'Kyrgyzstan', 'Kara Suu', 'Soko Airport');
insert into Airport (airport_id, country, city, name) values (9, 'Thailand', 'Phu Khiao', 'Antrim County Airport');
insert into Airport (airport_id, country, city, name) values (10, 'Indonesia', 'Galesong', 'William P Hobby Airport');
insert into Airport (airport_id, country, city, name) values (11, 'Portugal', 'Cruz', 'Black Hills Airport-Clyde Ice Field');
insert into Airport (airport_id, country, city, name) values (12, 'France', 'Nancy', 'Kish International Airport');
insert into Airport (airport_id, country, city, name) values (13, 'Palestinian Territory', 'Naḩḩālīn', 'Melbourne International Airport');
insert into Airport (airport_id, country, city, name) values (14, 'China', 'Situ', 'Lethem Airport');
insert into Airport (airport_id, country, city, name) values (15, 'China', 'Huangkeng', 'Ontario International Airport');
insert into Airport (airport_id, country, city, name) values (16, 'France', 'Bourgoin-Jallieu', 'Am Timan Airport');
insert into Airport (airport_id, country, city, name) values (17, 'Brazil', 'Xanxerê', 'Marina Municipal Airport');
insert into Airport (airport_id, country, city, name) values (18, 'Canada', 'Kingston', 'Montgomery County Airpark');
insert into Airport (airport_id, country, city, name) values (19, 'Philippines', 'Bantuanon', 'Khoram Abad Airport');
insert into Airport (airport_id, country, city, name) values (20, 'France', 'Bonneville', 'Sacheon Air Base/Airport');
insert into Airport (airport_id, country, city, name) values (21, 'Russia', 'Karasuk', 'General Manuel Serrano Airport');
insert into Airport (airport_id, country, city, name) values (22, 'Indonesia', 'Sendung', 'Canela Airport');
insert into Airport (airport_id, country, city, name) values (23, 'Colombia', 'San Francisco', 'Macenta Airport');
insert into Airport (airport_id, country, city, name) values (24, 'Israel', 'Hod HaSharon', 'Scribner State Airport');
insert into Airport (airport_id, country, city, name) values (25, 'Indonesia', 'Cisitu', 'Sir Abubakar Tafawa Balewa International Airport');
insert into Airport (airport_id, country, city, name) values (26, 'Malaysia', 'Kuantan', 'Falcon State Airport');
insert into Airport (airport_id, country, city, name) values (27, 'United States', 'Brooklyn', 'Iligan Airport');
insert into Airport (airport_id, country, city, name) values (28, 'France', 'Avignon', 'Jacksonville Executive at Craig Airport');
insert into Airport (airport_id, country, city, name) values (29, 'Indonesia', 'Kota Ternate', 'Barranca De Upia Airport');
insert into Airport (airport_id, country, city, name) values (30, 'Serbia', 'Bački Petrovac', 'Huehuetenango Airport');
insert into Airport (airport_id, country, city, name) values (31, 'Ukraine', 'Chulakivka', 'Monkey Mountain Airport');
insert into Airport (airport_id, country, city, name) values (32, 'Hungary', 'Zalaegerszeg', 'La Güera Airport');
insert into Airport (airport_id, country, city, name) values (33, 'Philippines', 'Pulilan', 'Springdale Municipal Airport');
insert into Airport (airport_id, country, city, name) values (34, 'China', 'Jiangnan', 'Monmouth Executive Airport');
insert into Airport (airport_id, country, city, name) values (35, 'Thailand', 'Thai Charoen', 'Bonn-Hangelar Airport');
insert into Airport (airport_id, country, city, name) values (36, 'China', 'Dongwan', 'Trent Lott International Airport');
insert into Airport (airport_id, country, city, name) values (37, 'Philippines', 'Angono', 'Eirunepé Airport');
insert into Airport (airport_id, country, city, name) values (38, 'Japan', 'Ishinomaki', 'Wynyard Airport');
insert into Airport (airport_id, country, city, name) values (39, 'Russia', 'Yermolayevo', 'Motueka Airport');
insert into Airport (airport_id, country, city, name) values (40, 'United States', 'Colorado Springs', 'Røros Airport');
insert into Airport (airport_id, country, city, name) values (41, 'Botswana', 'Letsheng', 'Comandante Ariston Pessoa Airport');
insert into Airport (airport_id, country, city, name) values (42, 'Finland', 'Rymättylä', 'Dera Ghazi Khan Airport');
insert into Airport (airport_id, country, city, name) values (43, 'Russia', 'Voyskovitsy', 'Randolph Air Force Base');
insert into Airport (airport_id, country, city, name) values (44, 'China', 'Hengzhou', 'Tolmachevo Airport');
insert into Airport (airport_id, country, city, name) values (45, 'Yemen', 'Shiḩan as Suflá', 'Parndana Airport');
insert into Airport (airport_id, country, city, name) values (46, 'Senegal', 'Ndofane', 'Pindiu Airport');
insert into Airport (airport_id, country, city, name) values (47, 'Ukraine', 'Kremidivka', 'Osmany International Airport');
insert into Airport (airport_id, country, city, name) values (48, 'Brazil', 'Santana do Livramento', 'Wamena Airport');
insert into Airport (airport_id, country, city, name) values (49, 'France', 'Besançon', 'Detroit Metropolitan Wayne County Airport');
insert into Airport (airport_id, country, city, name) values (50, 'Russia', 'Verkhnyaya Khava', 'Wallal Airport');
insert into Airport (airport_id, country, city, name) values (51, 'Colombia', 'Barranquilla', 'Port Said Airport');
insert into Airport (airport_id, country, city, name) values (52, 'China', 'Baishuitan', 'Ioannina Airport');
insert into Airport (airport_id, country, city, name) values (53, 'Chile', 'Cartagena', 'Shikarpur Airport');
insert into Airport (airport_id, country, city, name) values (54, 'Russia', 'Onega', 'Yecheon Airbase');
insert into Airport (airport_id, country, city, name) values (55, 'Nigeria', 'Ogurugu', 'Eagle Air Park');
insert into Airport (airport_id, country, city, name) values (56, 'Greece', 'Ágios Andréas', 'San Javier Airport');
insert into Airport (airport_id, country, city, name) values (57, 'Indonesia', 'Wunat', 'RAF Bentwaters');
insert into Airport (airport_id, country, city, name) values (58, 'South Korea', 'Kwangju', 'Warrnambool Airport');
insert into Airport (airport_id, country, city, name) values (59, 'Brazil', 'Nova Olímpia', 'Nomad River Airport');
insert into Airport (airport_id, country, city, name) values (60, 'China', 'Ewirgol', 'Tinson Pen Airport');
insert into Airport (airport_id, country, city, name) values (61, 'Philippines', 'Paoay', 'Port Macquarie Airport');
insert into Airport (airport_id, country, city, name) values (62, 'Somalia', 'Jilib', 'Takamatsu Airport');
insert into Airport (airport_id, country, city, name) values (63, 'China', 'Huotong', 'Onslow Airport');
insert into Airport (airport_id, country, city, name) values (64, 'Vietnam', 'Sadek', 'Springvale Airport');
insert into Airport (airport_id, country, city, name) values (65, 'Pakistan', 'Pindi Gheb', 'Juruena Airport');
insert into Airport (airport_id, country, city, name) values (66, 'China', 'Taozhuang', 'Manihiki Island Airport');
insert into Airport (airport_id, country, city, name) values (67, 'Armenia', 'Shnogh', 'Tulaghi Heliport');
insert into Airport (airport_id, country, city, name) values (68, 'China', 'Dakoutun', 'Madison Municipal Airport');
insert into Airport (airport_id, country, city, name) values (69, 'Portugal', 'Portela', 'Mc Alester Regional Airport');
insert into Airport (airport_id, country, city, name) values (70, 'Indonesia', 'Sendangagung', 'Koltsovo Airport');
insert into Airport (airport_id, country, city, name) values (71, 'Poland', 'Bęczarka', 'El Centro NAF Airport (Vraciu Field)');
insert into Airport (airport_id, country, city, name) values (72, 'Sweden', 'Tierp', 'Vinh Airport');
insert into Airport (airport_id, country, city, name) values (73, 'China', 'Nirji', 'Sharpe Field');
insert into Airport (airport_id, country, city, name) values (74, 'Afghanistan', 'Shibirghān', 'Alula Airport');
insert into Airport (airport_id, country, city, name) values (75, 'Germany', 'Bielefeld', 'Mallacoota Airport');
insert into Airport (airport_id, country, city, name) values (76, 'Thailand', 'Yarang', 'Tagula Airport');
insert into Airport (airport_id, country, city, name) values (77, 'Poland', 'Tarczyn', 'Port Sudan New International Airport');
insert into Airport (airport_id, country, city, name) values (78, 'Spain', 'Zaragoza', 'Bartlesville Municipal Airport');
insert into Airport (airport_id, country, city, name) values (79, 'Sweden', 'Stockholm', 'Yotvata Airfield');
insert into Airport (airport_id, country, city, name) values (80, 'Ukraine', 'Lisovi Sorochyntsi', 'El Tari Airport');
insert into Airport (airport_id, country, city, name) values (81, 'Philippines', 'Libertad', 'Fernando de Noronha Airport');
insert into Airport (airport_id, country, city, name) values (82, 'Netherlands', 'Hoorn', 'Haugesund Airport');
insert into Airport (airport_id, country, city, name) values (83, 'Yemen', 'Jiḩānah', 'California Redwood Coast-Humboldt County Airport');
insert into Airport (airport_id, country, city, name) values (84, 'Indonesia', 'Sukapura', 'Kiryat Shmona Airport');
insert into Airport (airport_id, country, city, name) values (85, 'Botswana', 'Palapye', 'Maramureș International Airport');
insert into Airport (airport_id, country, city, name) values (86, 'Serbia', 'Radojevo', 'Pécs-Pogány Airport');
insert into Airport (airport_id, country, city, name) values (87, 'Brazil', 'Barueri', 'Santa Maria da Vitória Airport');
insert into Airport (airport_id, country, city, name) values (88, 'Poland', 'Milanów', 'Gulgubip Airport');
insert into Airport (airport_id, country, city, name) values (89, 'Russia', 'Koshki', 'Reyes Murillo Airport');
insert into Airport (airport_id, country, city, name) values (90, 'Honduras', 'El Suyatal', 'Inácio Luís do Nascimento Airport');
insert into Airport (airport_id, country, city, name) values (91, 'Philippines', 'Umabay', 'Urzhar Airport');
insert into Airport (airport_id, country, city, name) values (92, 'Peru', 'Celendín', 'Valley International Airport');
insert into Airport (airport_id, country, city, name) values (93, 'Colombia', 'Floresta', 'Nîmes-Arles-Camargue Airport');
insert into Airport (airport_id, country, city, name) values (94, 'Russia', 'Selikhino', 'Alegrete Novo Airport');
insert into Airport (airport_id, country, city, name) values (95, 'Indonesia', 'Kalianget', 'Grand Marais Cook County Airport');
insert into Airport (airport_id, country, city, name) values (96, 'Central African Republic', 'Mobaye', 'General Leite de Castro Airport');
insert into Airport (airport_id, country, city, name) values (97, 'Portugal', 'Cabeço', 'Ndjili International Airport');
insert into Airport (airport_id, country, city, name) values (98, 'Indonesia', 'Kadurahayu', 'Harrismith Airport');
insert into Airport (airport_id, country, city, name) values (99, 'Japan', 'Ichinohe', 'Moody Air Force Base');
insert into Airport (airport_id, country, city, name) values (100, 'South Africa', 'Caledon', 'Bobo Dioulasso Airport');
insert into Airport (airport_id, country, city, name) values (101, 'Guatemala', 'San Bartolomé Milpas Altas', 'Cushing Municipal Airport');
insert into Airport (airport_id, country, city, name) values (102, 'Gambia', 'Baro Kunda', 'Shahid Ashrafi Esfahani Airport');
insert into Airport (airport_id, country, city, name) values (103, 'Serbia', 'Nakovo', 'Mount Keith Airport');
insert into Airport (airport_id, country, city, name) values (104, 'Kenya', 'Makueni', 'Zhezkazgan Airport');
insert into Airport (airport_id, country, city, name) values (105, 'Vietnam', 'Hưng Yên', 'Frankfurt-Hahn Airport');
insert into Airport (airport_id, country, city, name) values (106, 'Bangladesh', 'Dhaka', 'Alxa Right Banner Badanjilin Airport');
insert into Airport (airport_id, country, city, name) values (107, 'Philippines', 'Little Baguio', 'La Baule-Escoublac Airport');
insert into Airport (airport_id, country, city, name) values (108, 'United States', 'Harrisburg', 'Mount Hotham Airport');
insert into Airport (airport_id, country, city, name) values (109, 'Libya', 'Şurmān', 'Faya Largeau Airport');
insert into Airport (airport_id, country, city, name) values (110, 'Russia', 'Glinka', 'Nambaiyufa Airport');
insert into Airport (airport_id, country, city, name) values (111, 'Indonesia', 'Peuara', 'Carmelita Airport');
insert into Airport (airport_id, country, city, name) values (112, 'Vietnam', 'Khe Tre', 'Illinois Valley Regional Airport-Walter A Duncan Field');
insert into Airport (airport_id, country, city, name) values (113, 'Belgium', 'Namur', 'Santa Rosa International Airport');
insert into Airport (airport_id, country, city, name) values (114, 'Portugal', 'Espinheira', 'Stockholm Västerås Airport');
insert into Airport (airport_id, country, city, name) values (115, 'Peru', 'Huayllo', 'New Plymouth Airport');
insert into Airport (airport_id, country, city, name) values (116, 'China', 'Wuxi', 'Santa Vitória do Palmar Airport');
insert into Airport (airport_id, country, city, name) values (117, 'Kazakhstan', 'Stepnogorsk', 'Khark Island Airport');
insert into Airport (airport_id, country, city, name) values (118, 'Philippines', 'Tabio', 'Unalaska Airport');
insert into Airport (airport_id, country, city, name) values (119, 'Kyrgyzstan', 'Kaindy', 'Rzhevka Airport');
insert into Airport (airport_id, country, city, name) values (120, 'China', 'Luxi', 'Grantsburg Municipal Airport');
insert into Airport (airport_id, country, city, name) values (121, 'Cameroon', 'Eséka', 'Gustavo Rojas Pinilla International Airport');
insert into Airport (airport_id, country, city, name) values (122, 'Pakistan', 'Mach', 'Yeerqiang Airport');
insert into Airport (airport_id, country, city, name) values (123, 'Peru', 'Pataypampa', 'Bradshaw Army Airfield');
insert into Airport (airport_id, country, city, name) values (124, 'China', 'Tuojiang', 'Botopasi Airport');
insert into Airport (airport_id, country, city, name) values (125, 'China', 'Ji’an', 'Sierra Blanca Regional Airport');
insert into Airport (airport_id, country, city, name) values (126, 'Pakistan', 'Chak', 'Biaru Airport');
insert into Airport (airport_id, country, city, name) values (127, 'Philippines', 'Umingan', 'Umberto Modiano Airport');
insert into Airport (airport_id, country, city, name) values (128, 'Sweden', 'Helsingborg', 'Abha Regional Airport');
insert into Airport (airport_id, country, city, name) values (129, 'Sweden', 'Kungsör', 'Ozona Municipal Airport');
insert into Airport (airport_id, country, city, name) values (130, 'France', 'Issy-les-Moulineaux', 'Beale Air Force Base');
insert into Airport (airport_id, country, city, name) values (131, 'Sweden', 'Söderhamn', 'Fairchild Air Force Base');
insert into Airport (airport_id, country, city, name) values (132, 'South Africa', 'Vryburg', 'Hambantota Seaplane Base');
insert into Airport (airport_id, country, city, name) values (133, 'Poland', 'Głowno', 'Artesia Municipal Airport');
insert into Airport (airport_id, country, city, name) values (134, 'United States', 'New York City', 'Fua''amotu International Airport');
insert into Airport (airport_id, country, city, name) values (135, 'Ukraine', 'Velyka Bilozerka', 'Taganrog Yuzhny Airport');
insert into Airport (airport_id, country, city, name) values (136, 'China', 'Xinhui', 'Valdez Pioneer Field');
insert into Airport (airport_id, country, city, name) values (137, 'Thailand', 'Sathon', 'Peter O Knight Airport');
insert into Airport (airport_id, country, city, name) values (138, 'Philippines', 'Almeria', 'Capitan FAP Carlos Martinez De Pinillos International Airport');
insert into Airport (airport_id, country, city, name) values (139, 'Ukraine', 'Mahdalynivka', 'Pukaki Airport');
insert into Airport (airport_id, country, city, name) values (140, 'United Kingdom', 'Liverpool', 'Bilogai-Sugapa Airport');
insert into Airport (airport_id, country, city, name) values (141, 'Argentina', 'Pellegrini', 'Attu Heliport');
insert into Airport (airport_id, country, city, name) values (142, 'Chile', 'Concepción', 'Gan International Airport');
insert into Airport (airport_id, country, city, name) values (143, 'Guyana', 'Mahaica Village', 'Ouzinkie Airport');
insert into Airport (airport_id, country, city, name) values (144, 'China', 'Jiangcheng', 'Jaipur International Airport');
insert into Airport (airport_id, country, city, name) values (145, 'China', 'Tangqian', 'Watson Lake Airport');
insert into Airport (airport_id, country, city, name) values (146, 'China', 'Daban', 'Washington Island Airstrip');
insert into Airport (airport_id, country, city, name) values (147, 'China', 'Lingtou', 'Hermannsburg Airport');
insert into Airport (airport_id, country, city, name) values (148, 'Canada', 'Lamont', 'Zamboanga International Airport');
insert into Airport (airport_id, country, city, name) values (149, 'Tanzania', 'Kibondo', 'Baibara Airport');
insert into Airport (airport_id, country, city, name) values (150, 'Indonesia', 'Bojongbenteng', 'Roxas Airport');
insert into Airport (airport_id, country, city, name) values (151, 'Kenya', 'Kajiado', 'Hubli Airport');
insert into Airport (airport_id, country, city, name) values (152, 'China', 'Xunzhai', 'Macau International Airport');
insert into Airport (airport_id, country, city, name) values (153, 'Indonesia', 'Pandat', 'Mostyn Airport');
insert into Airport (airport_id, country, city, name) values (154, 'Philippines', 'San Mariano', 'Combolcha Airport');
insert into Airport (airport_id, country, city, name) values (155, 'Philippines', 'San Pedro', 'North Caicos Airport');
insert into Airport (airport_id, country, city, name) values (156, 'Russia', 'Ilanskiy', 'Herendeen Bay Airport');
insert into Airport (airport_id, country, city, name) values (157, 'Senegal', 'Saint-Louis', 'Gualeguaychu Airport');
insert into Airport (airport_id, country, city, name) values (158, 'China', 'Guojiaba', 'Inhambane Airport');
insert into Airport (airport_id, country, city, name) values (159, 'Portugal', 'Amadora', 'Cassilândia Airport');
insert into Airport (airport_id, country, city, name) values (160, 'Philippines', 'Baliuag Nuevo', 'Bulgan Sum Airport');
insert into Airport (airport_id, country, city, name) values (161, 'Brazil', 'Cachoeiro de Itapemirim', 'St Petersburg Clearwater International Airport');
insert into Airport (airport_id, country, city, name) values (162, 'Canada', 'Berthierville', 'Peshawar International Airport');
insert into Airport (airport_id, country, city, name) values (163, 'Israel', 'Na''ale', 'Sochi International Airport');
insert into Airport (airport_id, country, city, name) values (164, 'China', 'Renhe', 'Rouyn Noranda Airport');
insert into Airport (airport_id, country, city, name) values (165, 'Kuwait', 'Ar Rumaythīyah', 'Clinton Regional Airport');
insert into Airport (airport_id, country, city, name) values (166, 'France', 'Amiens', 'Dutchess County Airport');
insert into Airport (airport_id, country, city, name) values (167, 'Philippines', 'Tanlad', 'Springdale Municipal Airport');
insert into Airport (airport_id, country, city, name) values (168, 'Sweden', 'Lidingö', 'Imperial County Airport');
insert into Airport (airport_id, country, city, name) values (169, 'Yemen', 'Ḩabīl al Jabr', 'Daporijo Airport');
insert into Airport (airport_id, country, city, name) values (170, 'China', 'Yanqian', 'Decorah Municipal Airport');
insert into Airport (airport_id, country, city, name) values (171, 'Colombia', 'Plato', 'Shahroud Airport');
insert into Airport (airport_id, country, city, name) values (172, 'Nigeria', 'Abuochiche', 'Grand Geneva Resort Airport');
insert into Airport (airport_id, country, city, name) values (173, 'China', 'Fushan', 'Chuja Port Heliport');
insert into Airport (airport_id, country, city, name) values (174, 'Indonesia', 'Bojongsarung', 'Mc Guire Air Force Base');
insert into Airport (airport_id, country, city, name) values (175, 'Philippines', 'San Pedro', 'Drummond Airport');
insert into Airport (airport_id, country, city, name) values (176, 'China', 'Nanzhai', 'Suabi Airport');
insert into Airport (airport_id, country, city, name) values (177, 'China', 'Yanghuxiang', 'Outer Skerries Airport');
insert into Airport (airport_id, country, city, name) values (178, 'Afghanistan', 'Shīnḏanḏ', 'Žabljak Airport');
insert into Airport (airport_id, country, city, name) values (179, 'China', 'Shangcun', 'Nambucca Heads Airport');
insert into Airport (airport_id, country, city, name) values (180, 'Chad', 'Doba', 'Zorg en Hoop Airport');
insert into Airport (airport_id, country, city, name) values (181, 'Poland', 'Węgierska Górka', 'Beale Air Force Base');
insert into Airport (airport_id, country, city, name) values (182, 'Portugal', 'Guia', 'Zulu Inyala Airport');
insert into Airport (airport_id, country, city, name) values (183, 'United States', 'Oklahoma City', 'Craig Moffat Airport');
insert into Airport (airport_id, country, city, name) values (184, 'United States', 'Oklahoma City', 'Böblingen Flugfeld');
insert into Airport (airport_id, country, city, name) values (185, 'Finland', 'Kronoby', 'Central Nebraska Regional Airport');
insert into Airport (airport_id, country, city, name) values (186, 'Argentina', 'General Alvear', 'Saint-Brieuc-Armor Airport');
