insert into Flyer_Miles (fm_id, miles, description) values (1, 298, 'feugiat et eros');
insert into Flyer_Miles (fm_id, miles, description) values (2, 412, 'quam');
insert into Flyer_Miles (fm_id, miles, description) values (3, 184, 'consectetuer');
insert into Flyer_Miles (fm_id, miles, description) values (4, 294, 'ac enim');
insert into Flyer_Miles (fm_id, miles, description) values (5, 133, 'interdum');
insert into Flyer_Miles (fm_id, miles, description) values (6, 206, 'lobortis convallis');
insert into Flyer_Miles (fm_id, miles, description) values (7, 79, 'libero non');
insert into Flyer_Miles (fm_id, miles, description) values (8, 329, 'ut suscipit a');
insert into Flyer_Miles (fm_id, miles, description) values (9, 107, 'nulla neque libero');
insert into Flyer_Miles (fm_id, miles, description) values (10, 151, 'gravida');
insert into Flyer_Miles (fm_id, miles, description) values (11, 279, 'cursus urna ut');
