insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (1, 'Tarīm', 'Semampirbarat', 2975, 'Yemen', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (2, 'Kushikino', 'Bystrytsya', 7023, 'Japan', 'Ukraine');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (3, 'Blantyre', 'Pivijay', 2563, 'Malawi', 'Colombia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (4, 'Milići', 'Ar Rawnah', 2548, 'Bosnia and Herzegovina', 'Yemen');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (5, 'Dardhas', 'Jiefu', 2557, 'Albania', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (6, 'Salaya', 'Vurğun', null, 'Thailand', 'Azerbaijan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (7, 'Bazar-Korgon', 'Stockholm', 1534, 'Kyrgyzstan', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (8, 'Portão', 'Vilar do Pinheiro', 3409, 'Brazil', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (9, 'Fenshui', 'Nāḩiyat Baḩār', null, 'China', 'Iraq');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (10, 'Oslo', 'Pacarkeling', null, 'Norway', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (11, 'Anxiang', 'Ust-Maya', 6150, 'China', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (12, 'Bansalan', 'Jiangpan', 5576, 'Philippines', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (13, 'Angren', 'Taposan', null, 'Uzbekistan', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (14, 'Luo’ao', 'Nyköping', 6090, 'China', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (15, 'Renchaoxi', 'Mishan', 5538, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (16, 'Léfka', 'Horní Stropnice', 7236, 'Cyprus', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (17, 'Uherské Hradiště', 'Jiumen', 4072, 'Czech Republic', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (18, 'KwaMbonambi', 'Altay', 1609, 'South Africa', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (19, 'Seremban', 'Giồng Trôm', 7636, 'Malaysia', 'Vietnam');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (20, 'Moriyama', 'Pasarbaru', 8216, 'Japan', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (21, 'Bocana de Paiwas', 'Yingwusitang', null, 'Nicaragua', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (22, 'Huatanshan', 'Beixiaoying', 8216, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (23, 'Blerim', 'Łomazy', 4219, 'Albania', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (24, 'Surin', 'Viloco', 6974, 'Thailand', 'Bolivia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (25, 'Almenara', 'Viengxay', 5042, 'Brazil', 'Laos');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (26, 'Bokhan', 'Jurh', 6445, 'Russia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (27, 'Górki Wielkie', 'Kashin', 3395, 'Poland', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (28, 'Polešovice', 'Aba', 1616, 'Czech Republic', 'Nigeria');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (29, 'Maroanging', 'Guruafin', null, 'Indonesia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (30, 'San Vicente', 'Zhosaly', 2349, 'Philippines', 'Kazakhstan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (31, 'Şuwayr', 'Gongchenqiao', null, 'Yemen', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (32, 'Várzea', 'Mölndal', 9869, 'Portugal', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (33, 'Suwon-si', 'Shiqiao', 562, 'South Korea', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (34, 'Rathangan', 'Katsuta', null, 'Ireland', 'Japan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (35, 'Kafyr-Kumukh', 'Debesy', 4514, 'Russia', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (36, 'Roissy Charles-de-Gaulle', 'Widuchowa', null, 'France', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (37, 'Satovcha', 'Aranhas', 5406, 'Bulgaria', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (38, 'Aoji-ri', 'Bila Krynytsya', null, 'North Korea', 'Ukraine');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (39, 'Dizhai', 'Dianya', 681, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (40, 'Krasnystaw', 'Langenburg', 782, 'Poland', 'Canada');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (41, 'Luanshya', 'Dampit Satu', 6972, 'Zambia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (42, 'Emiliano Zapata', 'Kvasice', null, 'Mexico', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (43, 'Cergy-Pontoise', 'Opatovice nad Labem', null, 'France', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (44, 'Khayr Kōṯ', 'Mlonggo', 6499, 'Afghanistan', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (45, 'Pajoreja', 'Bến Cầu', null, 'Indonesia', 'Vietnam');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (46, 'Jardim', 'Dobje pri Planini', 4691, 'Brazil', 'Slovenia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (47, 'Hufang', 'Khulm', null, 'China', 'Afghanistan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (48, 'Hrazdan', 'Payabon', null, 'Armenia', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (49, 'Tanjungpati', 'Novaya Lyalya', 3756, 'Indonesia', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (50, 'Abakan', 'Bakıxanov', 2717, 'Russia', 'Azerbaijan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (51, 'Champaign', 'Benito Juarez', null, 'United States', 'Mexico');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (52, 'Malindi', 'Banqiao', 7290, 'Kenya', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (53, 'A-da-Gorda', 'Tor', 5800, 'Portugal', 'Egypt');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (54, 'Yangqiao', 'Phoenix', null, 'China', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (55, 'Mönsterås', 'Finspång', 8195, 'Sweden', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (56, 'Cungapmimbo', 'Patitírion', 9133, 'Indonesia', 'Greece');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (57, 'Yishi', 'Bīr Nabālā', 8624, 'China', 'Palestinian Territory');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (58, 'Zehak', 'Redinha', null, 'Iran', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (59, 'Nishishinminato', 'Všetaty', 2828, 'Japan', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (60, 'Alīābad', 'Shakhun’ya', null, 'Pakistan', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (61, 'Dundrum', 'Horad Pinsk', 6041, 'Ireland', 'Belarus');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (62, 'Stepanivka', 'Laweueng', 7650, 'Ukraine', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (63, 'Kanda', 'Aveleda', 6923, 'Japan', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (64, 'Leluo', 'Oxelösund', 6898, 'China', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (65, 'Pachīr wa Āgām', 'Stockholm', 9386, 'Afghanistan', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (66, 'Dolisie', 'Ad Dann', 7929, 'Republic of the Congo', 'Yemen');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (67, 'Al Mawşil al Jadīdah', 'Oemanu', 3078, 'Iraq', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (68, 'Ngorongoro', 'Feira de Santana', null, 'Tanzania', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (69, 'San Pedro', 'Jangkungkusumo', null, 'Mexico', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (70, 'Malati', 'Taouima', 9937, 'Indonesia', 'Morocco');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (71, 'Eleftheroúpolis', 'Caxarias', 2011, 'Greece', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (72, 'Long Beluah', 'Beishan', 2196, 'Indonesia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (73, 'Westport', 'Zhongxin', 5152, 'New Zealand', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (74, 'Qian’an', 'Oulmes', 9665, 'China', 'Morocco');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (75, 'Tân Châu', 'Santa Ana', 3978, 'Vietnam', 'Venezuela');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (76, 'La Soledad', 'Makabe', 6408, 'Mexico', 'Japan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (77, 'Yanghou', 'Kpalimé', 161, 'China', 'Togo');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (78, 'Padre Bernardo', 'Nanfeng', 394, 'Brazil', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (79, 'Talipan', 'Kentville', 8009, 'Philippines', 'Canada');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (80, 'Longgang', 'Nungga', null, 'China', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (81, 'Nansheng', 'Mirkovci', 4277, 'China', 'Croatia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (82, 'Ludu', 'Njurunda', 1284, 'China', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (83, 'Kyoto', 'Ostrów Mazowiecka', 3861, 'Japan', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (84, 'Ban Khlong Bang Sao Thong', 'Orneta', null, 'Thailand', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (85, 'Kirovsk', 'Phanom Sarakham', 7226, 'Russia', 'Thailand');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (86, 'Diancun', 'Boneng', 5758, 'China', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (87, 'Stare Kurowo', 'Wudui', 7307, 'Poland', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (88, 'Alaghsas', 'Głogówek', 3735, 'Niger', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (89, 'Mali Iđoš', 'Puerto Deseado', null, 'Serbia', 'Argentina');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (90, 'Pucara', 'Kanoya', 1718, 'Peru', 'Japan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (91, 'Xinjian', 'Shichuan', 8398, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (92, 'Shiliting', 'Jerada', 6582, 'China', 'Morocco');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (93, 'Nehe', 'Şaydnāyā', 9772, 'China', 'Syria');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (94, 'San Pedro', 'Besançon', 1556, 'Bolivia', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (95, 'كاف الجاع', 'São Mateus', 8414, 'Syria', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (96, 'Dzagam', 'Nantes', 1024, 'Azerbaijan', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (97, 'Pakel', 'Bojonglarang', 9927, 'Indonesia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (98, 'New Orleans', 'Chixi', 7601, 'United States', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (99, 'Tundagan', 'Yintang', 2935, 'Indonesia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (100, 'Kunyang', 'Stírion', 1205, 'China', 'Greece');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (101, 'Eišiškės', 'Zhamog', 4166, 'Lithuania', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (102, 'Santa Praxedes', 'Hobaramachi', null, 'Philippines', 'Japan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (103, 'Ryjewo', 'Huaidao', 384, 'Poland', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (104, 'Ocucaje', 'Blagnac', 8458, 'Peru', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (105, 'Kumbo', 'Cipaku', 8372, 'Cameroon', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (106, 'Utama Wetan', 'Cerenti', 9513, 'Indonesia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (107, 'Lianpeng', 'Três Passos', 1202, 'China', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (108, 'Nová Cerekev', 'Torino', null, 'Czech Republic', 'Italy');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (109, 'Qihama', 'Wuduhe', 2980, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (110, 'Kampungladang', 'Krajan Puru', 1662, 'Indonesia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (111, 'Dinititi', 'Portela', 6883, 'Indonesia', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (112, 'Rimouski', 'Maoya', null, 'Canada', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (113, 'Gujun', 'Nancy', 6993, 'China', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (114, 'Thị Trấn Tam Điệp', 'Pa Kham', null, 'Vietnam', 'Thailand');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (115, 'Chengyue', 'Harar', null, 'China', 'Ethiopia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (116, 'Seres', 'Ballinteer', 6855, 'Philippines', 'Ireland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (117, 'Khlong Hat', 'Palopo', 3372, 'Thailand', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (118, 'Pasiripis', 'Hutag', 800, 'Indonesia', 'Mongolia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (119, 'Llano Largo', 'Mbanza-Ngungu', 2622, 'Panama', 'Democratic Republic of the Congo');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (120, 'Nārang', 'Farroupilha', 3356, 'Pakistan', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (121, 'Taveiro', 'Provatás', 6643, 'Portugal', 'Greece');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (122, 'Staryy Oskol', 'Wu’erqihan', 4814, 'Russia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (123, 'Gununganyartambak Tengah', 'Far‘ūn', 8559, 'Indonesia', 'Palestinian Territory');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (124, 'Rietavas', 'Bergville', null, 'Lithuania', 'South Africa');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (125, 'Texíguat', 'Tecka', null, 'Honduras', 'Argentina');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (126, 'Rybí', 'Udomlya', 4446, 'Czech Republic', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (127, 'Zuogaimanma', 'Wufeng', 1017, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (128, 'Kota Kinabalu', 'Ligonggang', 6188, 'Malaysia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (129, 'Gaotian', 'Maragogi', 5850, 'China', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (130, 'Redondos', 'Cesson-Sévigné', 766, 'Portugal', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (131, 'La Plata', 'Urzuf', 5934, 'Colombia', 'Ukraine');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (132, 'Malawag', 'Muang Sam Sip', null, 'Philippines', 'Thailand');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (133, 'Xiaozhang', 'Liulin', 9461, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (134, 'Laingsburg', 'Wotho', 8522, 'South Africa', 'Marshall Islands');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (135, 'Bin Yauri', 'Oslo', 9457, 'Nigeria', 'Norway');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (136, 'Banjar Tibubiyu Kaja', 'Limen', 1392, 'Indonesia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (137, 'Novodvinsk', 'Sumberpinang Satu', 7320, 'Russia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (138, 'Chicago', 'Zábřeh', 223, 'United States', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (139, 'West Palm Beach', 'Wufeng', 9013, 'United States', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (140, 'Balogo', 'Rzhavki', 6644, 'Philippines', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (141, 'Rusip', 'Xuancheng', 4939, 'Indonesia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (142, 'Stockholm', 'Centralniy', null, 'Sweden', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (143, 'Banjar Jabejero', 'Samaro', 7555, 'Indonesia', 'Pakistan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (144, 'Shifan', 'Maroúsi', null, 'China', 'Greece');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (145, 'Baihua', 'Viļāni', 1003, 'China', 'Latvia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (146, 'Delod Pangkung', 'Kalibaru', 6546, 'Indonesia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (147, 'Manacapuru', 'Fengjiang', 4835, 'Brazil', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (148, 'Jishi', 'Kista', null, 'China', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (149, 'Su’ao', 'Taoxi', 1151, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (150, 'Cikadu', 'Caen', 1381, 'Indonesia', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (151, 'Nacaome', 'Shanling', 8086, 'Honduras', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (152, 'Mirny', 'Chernomorskiy', 1826, 'Russia', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (153, 'Ust’-Dzheguta', 'Siva', 1039, 'Russia', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (154, 'Moste', 'Sihe', 7722, 'Slovenia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (155, 'Selkirk', 'Puck', 7035, 'Canada', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (156, 'Yuefeng', 'Castanheiro do Sul', 6423, 'China', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (157, 'Siaton', 'Qianshan', 5382, 'Philippines', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (158, 'Lantian', 'Opinogóra Górna', null, 'China', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (159, 'Buyuan', 'Guodu', 1193, 'Philippines', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (160, 'Magallanes', 'Akouda', null, 'Philippines', 'Tunisia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (161, 'Den Chai', 'Cahul', 8878, 'Thailand', 'Moldova');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (162, 'Sioah', 'Panitian', 172, 'Indonesia', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (163, 'Xiangyangpu', 'Mulyorejo', 3235, 'China', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (164, 'Challas', 'Zhulin', 7463, 'Peru', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (165, 'Ágios Matthaíos', 'New Shagunnu', 6401, 'Greece', 'Nigeria');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (166, 'Lamovita', 'Stockholm', null, 'Bosnia and Herzegovina', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (167, 'Jingcheng', 'Uppsala', 3179, 'China', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (168, 'Esik', 'Jiuzhai', null, 'Kazakhstan', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (169, 'Dongdajie', 'Sacramento', 9758, 'China', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (170, 'Reshetylivka', 'Sancang', 1892, 'Ukraine', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (171, 'Mabuttal East', 'Bishan', 6330, 'Philippines', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (172, 'Iperu', 'Voloshka', 5153, 'Nigeria', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (173, 'Wolonio', 'Makariv', 9105, 'Indonesia', 'Ukraine');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (174, 'Vale de Rolas', 'Siepraw', 8983, 'Portugal', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (175, 'Kumo', 'Wuqu', 3668, 'Nigeria', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (176, 'Jielin', 'Atuntaqui', 1439, 'China', 'Ecuador');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (177, 'Wołczyn', 'Paitan Norte', null, 'Poland', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (178, 'Tournon-sur-Rhône', 'Chenqiao', null, 'France', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (179, 'Diekirch', 'Islamey', 9768, 'Luxembourg', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (180, 'Ganyi', 'Shahrīār', 1167, 'China', 'Iran');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (181, 'Baranusa', 'Kými', 4189, 'Indonesia', 'Greece');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (182, 'Sunzhuang', 'Dianzi', 8038, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (183, 'Tulsa', 'Iperó', null, 'United States', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (184, 'Campo Belo', 'Xinning', 8630, 'Brazil', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (185, 'Paso de Indios', 'Nangxian', 1849, 'Argentina', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (186, 'Yuejin', 'Pandansari', null, 'China', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (187, 'Nová Role', 'Kuala Pilah', 2960, 'Czech Republic', 'Malaysia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (188, 'Carmen de Viboral', 'Kediren', 2894, 'Colombia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (189, 'Shengmi', 'Cangchang', 7850, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (190, 'Belköl', 'Créteil', 4282, 'Kazakhstan', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (191, 'Ubinskoye', 'Santa Catalina - Dique Lujan', 5076, 'Russia', 'Argentina');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (192, 'Chernelytsya', 'Steblevë', 4046, 'Ukraine', 'Albania');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (193, 'Xiongzhou', 'Ayotupas', 9761, 'China', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (194, 'Naebugis', 'Parrsboro', null, 'Indonesia', 'Canada');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (195, 'Ladoeiro', 'El Obeid', 6237, 'Portugal', 'Sudan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (196, 'Ashcroft', 'Dawuhanmangli', 6595, 'Canada', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (197, 'Orvault', 'Magisterial', 1004, 'France', 'Mexico');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (198, 'Prince Albert', 'Non Sila', 9828, 'Canada', 'Thailand');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (199, 'Huoshaoping', 'Fray Bentos', null, 'China', 'Uruguay');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (200, 'Nan’an', 'Chuncheng', 3084, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (201, 'Toufang', 'Moncada', null, 'China', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (202, 'Zhoukou', 'Huang’ao', null, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (203, 'Kamenka', 'Rumenka', null, 'Russia', 'Serbia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (204, 'Hongqiao', 'Dobri Dol', 8571, 'China', 'Macedonia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (205, 'Xiaojin', 'El Corozo', null, 'China', 'Venezuela');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (206, 'Guaramirim', 'Funabashi', 2478, 'Brazil', 'Japan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (207, 'Mgachi', 'Borodinskiy', 1484, 'Russia', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (208, 'Rājo Khanāni', 'Castlebridge', 1805, 'Pakistan', 'Ireland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (209, 'Monte de Trigo', 'Abreus', 3390, 'Portugal', 'Cuba');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (210, 'Karanganyar', 'Pavlysh', 1015, 'Indonesia', 'Ukraine');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (211, 'Hudai', 'Jadi', null, 'China', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (212, 'Chinú', 'Vredefort', 5589, 'Colombia', 'South Africa');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (213, 'Gardutanjak', 'Jishigang', 7199, 'Indonesia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (214, 'Masvingo', 'Torslanda', 7366, 'Zimbabwe', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (215, 'Sigou', 'Konstantynów Łódzki', null, 'China', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (216, 'Shirone', 'Fuliang', 5323, 'Japan', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (217, 'Wārāh', 'Dashkawka', null, 'Pakistan', 'Belarus');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (218, 'Fort Lauderdale', 'Sogcho', 1530, 'United States', 'South Korea');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (219, 'Xingfeng', 'Jinta', 5078, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (220, 'Arenas', 'Gózd', 3376, 'Philippines', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (221, 'Sidem', 'Talawi', null, 'Indonesia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (222, 'Panamá', 'Węgliniec', 1576, 'Panama', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (223, 'Kassándreia', 'Bayeux', null, 'Greece', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (224, 'Skien', 'Waigete', null, 'Norway', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (225, 'Colorado Springs', 'La Virgen', 5968, 'United States', 'Costa Rica');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (226, 'Mautapaga Bawah', 'Orlovo', 3728, 'Indonesia', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (227, 'Prochowice', 'Saint-Pierre', null, 'Poland', 'Reunion');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (228, 'Fucun', 'Shijiang', 5146, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (229, 'Cujillo', 'Jagodnjak', 2632, 'Peru', 'Croatia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (230, 'Kedungbacin', 'Saint-Paul', 2016, 'Indonesia', 'Reunion');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (231, 'Jiulonggang', 'Hubei', 8037, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (232, 'Oslo', 'Laško', null, 'Norway', 'Slovenia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (233, 'Wangcheng', 'Bromont', 573, 'China', 'Canada');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (234, 'Lishan', 'Zhouzhuang', 9770, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (235, 'Ganta', 'Joal-Fadiout', 7819, 'Liberia', 'Senegal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (236, 'Danyang', 'Shenzhengqiao', 2791, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (237, 'Gamawa', 'El Guapinol', 8780, 'Nigeria', 'Honduras');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (238, 'Vouani', 'Talok', null, 'Comoros', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (239, 'Tanay', 'Shilovo', 1566, 'Philippines', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (240, 'Businga', 'Lidköping', 4288, 'Democratic Republic of the Congo', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (241, 'Nanjiao', 'Fresno', null, 'China', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (242, 'Štítná nad Vláří', 'Santa Ana', 2694, 'Czech Republic', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (243, 'Rambatan', 'Dal’nerechensk', null, 'Indonesia', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (244, 'Shemursha', 'Dongshan', null, 'Russia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (245, 'Samobor', 'Cidahu', null, 'Croatia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (246, 'Agía Varvára', 'Cancas', 3251, 'Greece', 'Peru');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (247, 'Cazin', 'Wuhu', 3137, 'Bosnia and Herzegovina', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (248, 'Chaniá', 'Przyborów', 9469, 'Greece', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (249, 'Xinbao', 'Sukowiryo', null, 'China', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (250, 'Chişinău', 'Kaom', null, 'Moldova', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (251, 'Vilémov', 'Sembakung', 4213, 'Czech Republic', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (252, 'Daxing', 'Narowlya', null, 'China', 'Belarus');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (253, 'Botou', 'Katovice', 1404, 'China', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (254, 'Bulungu', 'Cedar Rapids', 2984, 'Democratic Republic of the Congo', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (255, 'Balakhta', 'Ngrejo', null, 'Russia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (256, 'Oslo', 'Livadiya', 1580, 'Norway', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (257, 'Cuijiaqiao', 'Francisco Villa', 1598, 'China', 'Mexico');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (258, 'Gongli', 'Breves', 5644, 'China', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (259, 'Shi’ao', 'Bronnitsy', 8491, 'China', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (260, 'Naviraí', 'Cachipay', 7015, 'Brazil', 'Colombia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (261, 'Yeni Suraxanı', 'Natitingou', 7228, 'Azerbaijan', 'Benin');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (262, 'Fuwayriţ', 'San Gabriel', 3811, 'Qatar', 'Ecuador');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (263, 'Samoljica', 'Montigny-lès-Metz', 3861, 'Serbia', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (264, 'Marang', 'Golem', 1985, 'Indonesia', 'Albania');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (265, 'Haveli', 'Al Madān', null, 'Pakistan', 'Yemen');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (266, 'Rodolívos', 'Cerro Corá', 8643, 'Greece', 'Argentina');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (267, 'Tiehe', 'Täby', 8040, 'China', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (268, 'Wangcun', 'Herval', null, 'China', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (269, 'Phanna Nikhom', 'Zrenjanin', 7324, 'Thailand', 'Serbia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (270, 'Margaharja', 'Plan de Ayala', 3307, 'Indonesia', 'Mexico');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (271, 'Cajuru', 'Pule', 8712, 'Brazil', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (272, 'Pradera', 'Shangdu', 8860, 'Colombia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (273, 'Kotatengah', 'Panjāb', null, 'Indonesia', 'Afghanistan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (274, 'Crépy-en-Valois', 'New Bedford', 5578, 'France', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (275, 'Wedoro', 'Diancun', null, 'Indonesia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (276, 'Heze', 'Yaizu', null, 'China', 'Japan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (277, 'Litian', 'Ereencav', 1823, 'China', 'Mongolia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (278, 'Qixing', 'Wangchuanchang', null, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (279, 'Peishe', 'Solčava', 8310, 'China', 'Slovenia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (280, 'Magdalena', 'San Juan', 2342, 'Peru', 'Costa Rica');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (281, 'Buenavista', 'Vol’sk', 9803, 'Philippines', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (282, 'Rublëvo', 'Wichian Buri', 561, 'Russia', 'Thailand');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (283, 'Dongxin', 'Milton', 823, 'China', 'United Kingdom');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (284, 'Sundsvall', 'Ystad', 6054, 'Sweden', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (285, 'Laowobao', 'Changyanbao', 7598, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (286, 'Saba Yoi', 'Qingkou', 4720, 'Thailand', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (287, 'Nanyuan', 'Prroshyan', 9021, 'China', 'Armenia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (288, 'Desē', 'Gedian', 2095, 'Ethiopia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (289, 'Kotabumi', 'Umi', 5365, 'Indonesia', 'Japan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (290, 'Shuangtian', 'La Sarrosa', 7892, 'China', 'Honduras');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (291, 'Kangar', 'Girona', null, 'Malaysia', 'Spain');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (292, 'Castainço', 'Sumberpucung', 280, 'Portugal', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (293, 'Wilmington', 'Malhiao', 7356, 'United States', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (294, 'Tres Arroyos', 'Wulan', 8966, 'Argentina', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (295, 'Sevlievo', 'Ellös', 4402, 'Bulgaria', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (296, 'Volta Redonda', 'Aracataca', null, 'Brazil', 'Colombia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (297, 'Sobral da Abelheira', 'Odzi', null, 'Portugal', 'Zimbabwe');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (298, 'Żabno', 'Suresnes', null, 'Poland', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (299, 'Stockholm', 'Nerchinsk', 3852, 'Sweden', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (300, 'Kájov', 'Blagoveshchenka', 4499, 'Czech Republic', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (301, 'Chilliwack', 'Ingeniero Guillermo N. Juárez', 4728, 'Canada', 'Argentina');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (302, 'Kabo', 'Nantes', 2929, 'Central African Republic', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (303, 'Örbyhus', 'Cigadog', null, 'Sweden', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (304, 'Hội An', 'Bavorov', null, 'Vietnam', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (305, 'Jōetsu', 'Narva', null, 'Japan', 'Estonia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (306, 'Gândara', 'Shilipu', 352, 'Portugal', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (307, 'Tékane', 'Xinkai', null, 'Mauritania', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (308, 'Limón', 'Dvůr Králové nad Labem', null, 'Costa Rica', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (309, 'Lancaster', 'Banī Suhaylā', null, 'United States', 'Palestinian Territory');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (310, 'Popielów', 'Umuquena', 8027, 'Poland', 'Venezuela');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (311, 'Gobojango', 'Quva', 3512, 'Botswana', 'Uzbekistan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (312, 'Zouiat ech Cheïkh', 'Cacoal', 5268, 'Morocco', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (313, 'Koźle', 'Batiano', 6837, 'Poland', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (314, 'Puyang', 'Mariestad', null, 'China', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (315, 'Duofudu', 'Yuhuazhai', 3393, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (316, 'Město Libavá', 'Ouadda', null, 'Czech Republic', 'Central African Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (317, 'Skanör', 'Barraute', 5913, 'Sweden', 'Canada');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (318, 'Karangsuko', 'Cergy-Pontoise', 9441, 'Indonesia', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (319, 'Nyurba', 'Oshawa', 8740, 'Russia', 'Canada');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (320, 'Caohezhang', 'Rogóźno', null, 'China', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (321, 'Pepe', 'Raga', 554, 'Indonesia', 'South Sudan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (322, 'Zubtsov', 'Cashel', null, 'Russia', 'Ireland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (323, 'Rupe', 'Brochów', 168, 'Indonesia', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (324, 'San Francisco', 'Cañas', 7339, 'Philippines', 'Costa Rica');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (325, 'Selebi-Phikwe', 'Yanjiang', 444, 'Botswana', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (326, 'Erdenet', 'Bondo', null, 'Mongolia', 'Democratic Republic of the Congo');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (327, 'Castro', 'Eucaliptus', 3666, 'Brazil', 'Bolivia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (328, 'Xiejiaya', 'Xijiang', 670, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (329, 'Negreiros', 'Saint-Jouan-des-Guérets', 4859, 'Portugal', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (330, 'Vidin', 'Katipunan', null, 'Bulgaria', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (331, 'Puncaksempur', 'Hampton', 9642, 'Indonesia', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (332, 'Ortiga', 'Lekaj', 7369, 'Portugal', 'Albania');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (333, 'Francisco I Madero', 'Longxi', null, 'Mexico', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (334, 'Tougan', 'Tanjung Pandan', 3819, 'Burkina Faso', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (335, 'Schiedam postbusnummers', 'Armamar', 8572, 'Netherlands', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (336, 'Mojogajeh', 'Chumpi', 142, 'Indonesia', 'Peru');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (337, 'Lutoryż', 'Reno', 4966, 'Poland', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (338, 'Åkersberga', 'Limatambo', 2398, 'Sweden', 'Peru');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (339, 'Santa Cruz', 'Nsok', null, 'Philippines', 'Equatorial Guinea');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (340, 'Kralupy nad Vltavou', 'Uspenka', null, 'Czech Republic', 'Ukraine');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (341, 'Suwaru', 'Tyresö', null, 'Indonesia', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (342, 'Wucheng', 'Sunnyvale', 6302, 'China', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (343, 'Aikmel', 'Sergelen', 3160, 'Indonesia', 'Mongolia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (344, 'Amboanjo', 'Mar del Plata', 8838, 'Madagascar', 'Argentina');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (345, 'Nobres', 'Riangwale', 2696, 'Brazil', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (346, 'Coishco', 'Várzea da Palma', 270, 'Peru', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (347, 'Lile', 'Jianshe', 8825, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (348, 'Cajamar', 'Pasirgaru', 5283, 'Brazil', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (349, 'Bhawāna', 'Zhangdian', 9038, 'Pakistan', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (350, 'Liudaogou', 'Normandin', null, 'China', 'Canada');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (351, 'Hitiaa', 'Amirabad', 9007, 'French Polynesia', 'Pakistan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (352, 'Temanjang', 'Drawsko', 907, 'Indonesia', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (353, 'Santa Rosa', 'Miłosław', 2241, 'Mexico', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (354, 'Maticmatic', 'Koua', 4955, 'Philippines', 'Comoros');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (355, 'Tucdao', 'Gowurdak', 9026, 'Philippines', 'Turkmenistan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (356, 'Asamankese', 'Skhodnya', 1138, 'Ghana', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (357, 'Jurak Lao’', 'Sinait', 5802, 'Indonesia', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (358, 'Bugojno', 'Buenos Aires', 7436, 'Bosnia and Herzegovina', 'Mexico');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (359, 'Zhukovskiy', 'Kotabaru Hilir', null, 'Russia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (360, 'Voznesenskoye', 'Abucay', 7275, 'Russia', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (361, 'Renhe', 'Vila Flor', 4431, 'China', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (362, 'Aldeias de Cima', 'Puerto Cisnes', 8013, 'Portugal', 'Chile');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (363, 'Huilelot', 'El Paso', 8562, 'Indonesia', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (364, 'Ajasse Ipo', 'Yerazgavors', 5414, 'Nigeria', 'Armenia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (365, 'Yangsi', 'Rio Grande', 9672, 'China', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (366, 'Makui', 'Hwawŏn', null, 'Indonesia', 'South Korea');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (367, 'Genisséa', 'Komyshnya', null, 'Greece', 'Ukraine');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (368, 'Ciwidara', 'Alor Setar', 2579, 'Indonesia', 'Malaysia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (369, 'Longde Chengguanzhen', 'Batulawang', 5421, 'China', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (370, 'Zongzhai', 'Banjar Bias', 1890, 'China', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (371, 'Brunssum', 'Ústí nad Labem', null, 'Netherlands', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (372, 'Almaty', 'Verkhniy Mamon', 5830, 'Kazakhstan', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (373, 'Lugait', 'Hatavch', null, 'Philippines', 'Mongolia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (374, 'Tulsīpur', 'Skalat', 3968, 'Nepal', 'Ukraine');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (375, 'Tegalgunung', 'Fujikawaguchiko', null, 'Indonesia', 'Japan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (376, 'Carmen de Viboral', 'Guantun', 7905, 'Colombia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (377, 'Cikuya', 'Horta', 9468, 'Indonesia', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (378, 'Shuangyang', 'Ålesund', 4508, 'China', 'Norway');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (379, 'Yuli', 'Ameixoeira', 4139, 'Nigeria', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (380, 'Angoulême', 'Doljo', 2474, 'France', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (381, 'Brněnec', 'Beishan', 4160, 'Czech Republic', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (382, 'Goyty', 'Barice', null, 'Russia', 'Bosnia and Herzegovina');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (383, 'Venustiano Carranza', 'Batulayang', 8249, 'Mexico', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (384, 'Dobřany', 'Urachiche', 4746, 'Czech Republic', 'Venezuela');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (385, 'Reina Mercedes', 'Tumpang Satu', 4475, 'Philippines', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (386, 'Huanxi', 'Amirabad', 4810, 'China', 'Pakistan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (387, 'Karangan', 'Mabiton', null, 'Indonesia', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (388, 'Abóboda', 'Zhenlai', 9498, 'Portugal', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (389, 'Jinluo', 'Dvorovi', 7941, 'China', 'Bosnia and Herzegovina');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (390, 'Trondheim', 'Furudate', 3666, 'Norway', 'Japan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (391, 'Mirebalais', 'Paris 02', 7655, 'Haiti', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (392, 'Xai-Xai', 'T’ianet’i', 6254, 'Mozambique', 'Georgia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (393, 'Alminhas', 'Kolaka', 5483, 'Portugal', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (394, 'Rude', 'Cikawung', 4790, 'Croatia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (395, 'Las Toscas', 'Xinjia', 7529, 'Argentina', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (396, 'Jinzhou', 'Saint-Bruno-de-Montarville', null, 'China', 'Canada');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (397, 'Chumphon', 'Priyutovo', 5041, 'Thailand', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (398, 'Bagaces', 'Palma De Mallorca', 1193, 'Costa Rica', 'Spain');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (399, 'Kozel’shchyna', 'Pskov', 4426, 'Ukraine', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (400, 'La Breita', 'Bang Ban', 8932, 'Peru', 'Thailand');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (401, 'Oslo', 'Pengwan', 600, 'Norway', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (402, 'Hachinohe', 'Mogi das Cruzes', 6844, 'Japan', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (403, 'Sanhui', 'Ūdalah', 2495, 'China', 'Palestinian Territory');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (404, 'Tonj', 'Muaralabuh', null, 'South Sudan', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (405, 'Triandría', 'Dowr-e Rabāţ', null, 'Greece', 'Afghanistan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (406, 'Qiandeng', 'Wanshan', 3703, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (407, 'Paurito', 'Kedung', 8380, 'Bolivia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (408, 'São Lourenço da Mata', 'Campaka', 3696, 'Brazil', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (409, 'Flores da Cunha', 'Guaiúba', 5917, 'Brazil', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (410, 'Lanyang', 'Kiambu', 4007, 'China', 'Kenya');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (411, 'Bauru', 'Gyamco', 6500, 'Brazil', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (412, 'Nakambala', 'Guadalupe Victoria', 4124, 'Zambia', 'Mexico');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (413, 'Midrand', 'Hörby', null, 'South Africa', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (414, 'Pantaibesar', 'Fengjiang', 9493, 'Indonesia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (415, 'Tangchijie', 'Nanhai', 4193, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (416, 'Luján', 'Sakon Nakhon', null, 'Argentina', 'Thailand');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (417, 'Girona', 'Rio Branco', 8969, 'Spain', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (418, 'Pirg', 'Plérin', 3969, 'Albania', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (419, 'Bancar', 'Nam Đàn', null, 'Indonesia', 'Vietnam');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (420, 'Feričanci', 'Sukarame', null, 'Croatia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (421, 'Ramat Yishay', 'Molepolole', 7618, 'Israel', 'Botswana');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (422, 'Lynn', 'Erdaobaihe', 8218, 'United States', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (423, 'Cikou', 'Mato Cheirinhos', 6198, 'China', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (424, 'Puerto Quijarro', 'Soa', 3852, 'Bolivia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (425, 'Qŭshkŭpir', 'Paraíso das Águas', 7589, 'Uzbekistan', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (426, 'Wuxiang', 'Olenegorsk', null, 'China', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (427, 'Lembur Tengah', 'Sena', 5080, 'Indonesia', 'Thailand');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (428, 'Panikihan', 'Quebrada de Arena', 3312, 'Philippines', 'Honduras');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (429, 'Novocherkassk', 'Nieborów', 9464, 'Russia', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (430, 'Jeonju', 'Grenoble', 6809, 'South Korea', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (431, 'Skövde', 'Palmira', 5260, 'Sweden', 'Cuba');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (432, 'Sobreira', 'Yên Bái', 3867, 'Portugal', 'Vietnam');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (433, 'Banjar Bias', 'Bobrov', 6241, 'Indonesia', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (434, 'Pivovarikha', 'Guzhen', 3758, 'Russia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (435, 'Tampa', 'Lomintsevskiy', 9258, 'United States', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (436, 'Guofu', 'Domaniewice', 6233, 'China', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (437, 'Huayang', 'Erie', 6432, 'China', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (438, 'Wawa', 'Andekantor', 1169, 'Nigeria', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (439, 'Sañgay', 'Yijiang', 5705, 'Philippines', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (440, 'Funabashi', 'Dongyuan', 698, 'Japan', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (441, 'Tufang', 'Osa', 7264, 'China', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (442, 'Vardenik', 'Rimba Sekampung', 557, 'Armenia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (443, 'Jishu', 'Yangji', null, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (444, 'Riangderi', 'Xiashitai', null, 'Indonesia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (445, 'Tal’ne', 'Kosonsoy Shahri', 1694, 'Ukraine', 'Uzbekistan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (446, 'Caldas Novas', 'Buga', null, 'Brazil', 'Mongolia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (447, 'Dibba Al-Hisn', 'Longzhouwan', null, 'United Arab Emirates', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (448, 'Stockholm', 'Río Grande', null, 'Sweden', 'Argentina');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (449, 'Jamaica', 'Jiazi', 7162, 'United States', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (450, 'Solok', 'Perez', null, 'Indonesia', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (451, 'Romanovskaya', 'Červené Pečky', null, 'Russia', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (452, 'Bořetice', 'Cunha', 4117, 'Czech Republic', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (453, 'Qincheng', 'Moyo', null, 'China', 'Uganda');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (454, 'Biting', 'Svalöv', null, 'Indonesia', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (455, 'Ivouani', 'Goraj', 201, 'Comoros', 'Poland');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (456, 'Baklashi', 'Sangar Sarāy', 4544, 'Russia', 'Afghanistan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (457, 'Hezhai', 'San Carlos', 8514, 'China', 'Peru');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (458, 'Irati', 'Bogorame', 6169, 'Brazil', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (459, 'Samangawah', 'Créteil', null, 'Indonesia', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (460, 'São José do Rio Pardo', 'El Lolo', 4684, 'Brazil', 'Honduras');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (461, 'Nalbandyan', 'Zala', 6280, 'Armenia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (462, 'Morales', 'Montpellier', 7381, 'Colombia', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (463, 'Ángeles', 'Laventille', 397, 'Costa Rica', 'Trinidad and Tobago');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (464, 'Changbu', 'Anton', 537, 'China', 'Bulgaria');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (465, 'Moca', 'Ardirejo', null, 'Dominican Republic', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (466, 'Daogao', 'Sirājganj', 9547, 'China', 'Bangladesh');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (467, 'Arcossó', 'Saint-Lô', 764, 'Portugal', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (468, 'Vlachovo Březí', 'Mathakola', 4008, 'Czech Republic', 'Botswana');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (469, 'Vélizy-Villacoublay', 'Sobreiro', null, 'France', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (470, 'Fort Worth', 'Bastia', 2352, 'United States', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (471, 'Salgueiro', 'San Marcos', 7598, 'Brazil', 'Mexico');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (472, 'Sacramento', 'Sydney', 5658, 'United States', 'Australia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (473, 'Los Andes', 'Santiago do Cacém', 2750, 'Colombia', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (474, 'Ciudian', 'El Progreso', 1828, 'Indonesia', 'Panama');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (475, 'San Bernardino', 'Cabak Satu', 1991, 'United States', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (476, 'Busia', 'Talghar', 2842, 'Kenya', 'Kazakhstan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (477, 'Ostrožská Nová Ves', 'Candelária', 2858, 'Czech Republic', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (478, 'Yingchengzi', 'Jindayris', 8387, 'China', 'Syria');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (479, 'Melekeok Village', 'Shikhazany', null, 'Palau', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (480, 'Kimanuit', 'Bamusso', null, 'Philippines', 'Cameroon');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (481, 'Penedo', 'Blatná', 1380, 'Brazil', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (482, 'Banjar Baleagung', 'Menzel Abderhaman', 8609, 'Indonesia', 'Tunisia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (483, 'Huangzhuang', 'Jamundí', null, 'China', 'Colombia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (484, 'Dĩ An', 'Saint Louis', 8638, 'Vietnam', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (485, 'Gostivar', 'Zásmuky', 8687, 'Macedonia', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (486, 'Nogent-le-Rotrou', 'Miguel Pereira', null, 'France', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (487, 'Cibungur', 'Reims', null, 'Indonesia', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (488, 'Yaogou', 'Zhovkva', 9720, 'China', 'Ukraine');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (489, 'Chirpan', 'Palmeiros', null, 'Bulgaria', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (490, 'Vitali', 'San José', 8833, 'Philippines', 'Paraguay');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (491, 'Quintã', 'Lillers', 1613, 'Portugal', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (492, 'Guia', 'Guantian', 1725, 'Portugal', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (493, 'Poniklá', 'Longzui', null, 'Czech Republic', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (494, 'Victoria', 'New York City', 5943, 'Philippines', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (495, 'Fukuoka-shi', 'Masparrito', 1485, 'Japan', 'Venezuela');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (496, 'Moyuan', 'Jianling', null, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (497, 'Kidangbang', 'Xiaoshiqiao', 3443, 'Indonesia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (498, 'Ouadda', 'Āl Ma‘ūdah', 7144, 'Central African Republic', 'Yemen');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (499, 'Imishli', 'San Rafael', null, 'Azerbaijan', 'Costa Rica');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (500, 'Cisewu', 'Las Flores', null, 'Indonesia', 'Mexico');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (501, 'Tauca', 'Zoumaping', 7324, 'Peru', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (502, 'Palma De Mallorca', 'Zhaigang', 8127, 'Spain', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (503, 'Chitose', 'Lañgub', 7180, 'Japan', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (504, 'Zhuqi', 'Aras-asan', 4914, 'China', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (505, 'Garango', 'Allacapan', null, 'Burkina Faso', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (506, 'Sydney', 'Riobamba', 7541, 'Australia', 'Ecuador');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (507, 'Wugong', 'Hailang', 8168, 'China', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (508, 'Qinshan', 'Kungsbacka', null, 'China', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (509, 'Toyohashi', 'Beiyang', null, 'Japan', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (510, 'Villa Altagracia', 'Pataruman', 2415, 'Dominican Republic', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (511, 'Sibay', 'Depapre', null, 'Russia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (512, 'Abidjan', 'Içara', 804, 'Ivory Coast', 'Brazil');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (513, 'Gabasumdo', 'Philadelphia', 2785, 'China', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (514, 'Huolongping', 'Palapye', null, 'China', 'Botswana');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (515, 'Kitakyūshū', 'Arcangel', 2999, 'Japan', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (516, 'Vrachnaíika', 'Jajawai', 8572, 'Greece', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (517, 'Haizigou', 'Ostrožská Lhota', 2349, 'China', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (518, 'Huashi', 'Iowa City', 1565, 'China', 'United States');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (519, 'Youzai', 'Laguna Limpia', 3058, 'China', 'Argentina');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (520, 'Bilajer', 'San Jose', 801, 'Azerbaijan', 'Mexico');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (521, 'Tours', 'Xilong', 2139, 'France', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (522, 'Nubl', 'Krajan Tanjungrejo', 3328, 'Syria', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (523, 'Ishim', 'Panjakent', 1453, 'Russia', 'Tajikistan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (524, 'Kebonkai', 'Itapé', 7780, 'Indonesia', 'Paraguay');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (525, 'Oslo', 'Cergy-Pontoise', null, 'Norway', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (526, 'Mundolsheim', 'Tapada das Mercês', 7312, 'France', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (527, 'Pontal', 'Runović', 5075, 'Brazil', 'Croatia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (528, 'Sorren Daya', 'Paris 16', 8589, 'Indonesia', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (529, 'Strašice', 'Fuyang', 9571, 'Czech Republic', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (530, 'Mont-Tremblant', 'Boje', null, 'Canada', 'Nigeria');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (531, 'Mirzec', 'Klokot', 2880, 'Poland', 'Kosovo');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (532, 'Vatutino', 'Sūq ar Rabū‘', 6737, 'Russia', 'Yemen');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (533, 'Khagrachhari', 'Iroquois Falls', 8258, 'Bangladesh', 'Canada');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (534, 'Babushkin', 'Xiehu', 2984, 'Russia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (535, 'Mulyo', 'Floirac', 7316, 'Indonesia', 'France');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (536, 'Natividade', 'Aḑ Ḑil‘', 8643, 'Brazil', 'Yemen');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (537, 'Luyang', 'Ath', null, 'China', 'Belgium');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (538, '‘Ābūd', 'Ejidal', 9723, 'Palestinian Territory', 'Mexico');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (539, 'Khok Charoen', 'Nesovice', 8645, 'Thailand', 'Czech Republic');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (540, 'Šipovo', 'Karagandy', 784, 'Bosnia and Herzegovina', 'Kazakhstan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (541, 'Aţ Ţawīlah', 'Xinan', 5712, 'Yemen', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (542, 'Agdangan', 'Songea', 2645, 'Philippines', 'Tanzania');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (543, 'Gereykhanovskoye', 'Rangah', null, 'Russia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (544, 'Shatki', 'Kagay', 2155, 'Russia', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (545, 'Yangxunqiao', 'Kabacan', 6400, 'China', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (546, 'Nanshi', 'Lewopao', 6548, 'China', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (547, 'Västerås', 'Gritsovskiy', 6266, 'Sweden', 'Russia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (548, 'Fāraskūr', 'Hushaat', 6392, 'Egypt', 'Mongolia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (549, 'Terrugem', 'Magdalena', null, 'Portugal', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (550, 'Ardabīl', 'Uppsala', 9492, 'Iran', 'Sweden');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (551, 'Conchal', 'Shigutang', 8711, 'Brazil', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (552, 'Asenovgrad', 'Tatsuno', null, 'Bulgaria', 'Japan');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (553, 'Portel', 'Tadmur', 8813, 'Brazil', 'Syria');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (554, 'Hot', 'Shuangtang', 4787, 'Albania', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (555, 'Słotowa', 'Hamberang Sabrang', 6951, 'Poland', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (556, 'Lecherías', 'Zhenqiao', 9840, 'Venezuela', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (557, 'Glempang Tengah', 'Kertahayu', null, 'Indonesia', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (558, 'Rio', 'Busay', 6403, 'Portugal', 'Philippines');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (559, 'Sali', 'Xiangyanglu', 6478, 'Croatia', 'China');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (560, 'Sävedalen', 'Mosteiros', 1698, 'Sweden', 'Portugal');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (561, 'Wanhu', 'Heliconia', 2136, 'China', 'Colombia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (562, 'Västra Frölunda', 'Babakanbandung', 7355, 'Sweden', 'Indonesia');
insert into Route (route_id, sourcecity, destcity, estdistance, srccountry, destcountry) values (563, 'Kepel', 'Monaghan', 272, 'Indonesia', 'Ireland');
